### ISSUE TITLE
Building backend

### ISSUE THREAD

**Issue by morphers82** [ChainTerra/BTCLT-Guide#3] opened 2021-05-20 15:57 UTC
Its probably an issue with the backend code for bitclout but
when I try to build the backend using: "docker build -t ubuntu-test:latest ."
I have this error:

Step 6/23 : COPY backend/go.mod backend/
COPY failed: file not found in build context or excluded by .dockerignore: stat backend/go.mod: file does not exist

**Comment by Mentors4EDU** [comment] 2021-05-20 17:23
Seems to be a problem here too: https://github.com/bitclout/core/runs/2611851151
Will look into it once BitClout updates its code.

**Comment by Mentors4EDU** [comment] 2021-05-20 17:27
I think it might be related to how the `WORKDIR` was labeled on that Dockerfile.

**Comment by Mentors4EDU** [comment] 2021-05-21 02:33
Hi, she closed the issue saying it is `..` as the build context but I don't think that is the problem. I may just try forking the core repo and fixing the paths myself or will see what I can do as a quick fix. Their CI also had build errors.

https://github.com/bitclout/backend/issues/10#issuecomment-845605011

**Comment by Mentors4EDU** [comment] 2021-05-21 03:01
I reproduced the same error:
https://github.com/bitclout/backend/issues/10#issuecomment-845615427

I will be looking into it, and might use buildkit.

Also I don't think there is a `..` built context. `.` is correct and not sure why I was told that.

**Comment by Mentors4EDU** [comment] 2021-05-30 21:32
Should be fixed w/ a9de7daf642c396995ead27c45e6dc21deb810da
Try `docker build -t backend ..`

**Closed by Mentors4EDU** 2021-05-30 21:32 UTC
